### ISSUE TITLE
Love.js error on first load

### ISSUE THREAD

**Issue by Sheepolution** [Sheepolution/love-fiddle#1]
When a user opens LÖVE Fiddle for the first time, they will get an alert:
> "An error occurred before the game window could be initialised. Please check the console!

Looking in the console we find the following error:
`Could not open file __temp0. Does not exist.`

[js.lua was changed](https://github.com/Sheepolution/love-fiddle/blob/master/lua/js.lua#L45) to include `FS.mkdirTree`, as without it we would get the above error constantly. Yet somehow it won't work on first load.

**Comment by Sheepolution** [comment]
@MrcSnm Any ideas why this error occurs? I added the `FS.mkdirTree` as a quick hack to get this working, but best would be if I used your code without changes. I just wasn't able to figure out how to prevent the error.

See [main.lua](https://github.com/Sheepolution/love-fiddle/blob/master/lua/main.lua) and [LÖVE Fiddle](https://sheepolution.com/love/) for some context.

**Comment by MrcSnm** [comment]
I remember that there was some need to overwrite some part of the generated love.js code with relation to some FS module which I don't remember right now.

I'm not really active anymore in the Love2D community since I've been working in my own engine.

The other thing is that:

Avoid completely the webDB that I have tried using. After some deep reconsiderations, it should be removed because the generated code with EMScripten actually has some kind of internal caching, so it isn't always taking information from the local database, so, even if it does simulate completely how EMScripten works, it won't do any good because of this existing cache.

You can also freely issue pull requests to my code, if you think you fixed it, the PRs are open and I'm willing to merge them so there is no problem.

**Comment by Sheepolution** [comment]
Thanks. I removed the webDB part, and was able to fix the issue by simply using `love.filesystem.write` to ensure that the directroy exists before it is accessed by FS.
